model:
  protocols: ["AND"]
  mi_values: [0.2]
  seed_budgets: [30]
  ss_methods: [
    "deg_c",
    "D^deg_c",
    "deg_cd",
    "D^deg_cd",
    "nghb_1s",
    "D^nghb_1s",
    "nghb_sd",
    "D^nghb_sd",
    "random",
    "D^random",
  ]

logging:
  full_output_frequency: -1
  compress_to_zip: True
  out_dir: "./data/raw_results_2nd/var_actors/series_1"  # <- select proper path according to the bach name

networks: [
  #  VAR_ACTORS SERIES 1
  "data-networks_sf-var_actors-series_1-1",
  "data-networks_sf-var_actors-series_1-2",
  "data-networks_sf-var_actors-series_1-3",
  "data-networks_sf-var_actors-series_1-4",
  "data-networks_sf-var_actors-series_1-5",
  "data-networks_sf-var_actors-series_1-6",
  "data-networks_sf-var_actors-series_1-7",
  "data-networks_sf-var_actors-series_1-8",
  "data-networks_sf-var_actors-series_1-9",
  "data-networks_sf-var_actors-series_1-10",
  "data-networks_sf-var_actors-series_1-11",
  "data-networks_sf-var_actors-series_1-12",
  "data-networks_sf-var_actors-series_1-13",
  "data-networks_sf-var_actors-series_1-14",
  "data-networks_sf-var_actors-series_1-15",
  "data-networks_sf-var_actors-series_1-16",
  "data-networks_sf-var_actors-series_1-17",
  "data-networks_sf-var_actors-series_1-18",
  "data-networks_sf-var_actors-series_1-19",
  "data-networks_sf-var_actors-series_1-20",
  #  VAR_ACTORS SERIES 2
  # "data-networks_sf-var_actors-series_2-1",
  # "data-networks_sf-var_actors-series_2-2",
  # "data-networks_sf-var_actors-series_2-3",
  # "data-networks_sf-var_actors-series_2-4",
  # "data-networks_sf-var_actors-series_2-5",
  # "data-networks_sf-var_actors-series_2-6",
  # "data-networks_sf-var_actors-series_2-7",
  # "data-networks_sf-var_actors-series_2-8",
  # "data-networks_sf-var_actors-series_2-9",
  # "data-networks_sf-var_actors-series_2-10",
  # "data-networks_sf-var_actors-series_2-11",
  # "data-networks_sf-var_actors-series_2-12",
  # "data-networks_sf-var_actors-series_2-13",
  # "data-networks_sf-var_actors-series_2-14",
  # "data-networks_sf-var_actors-series_2-15",
  # "data-networks_sf-var_actors-series_2-16",
  # "data-networks_sf-var_actors-series_2-17",
  # "data-networks_sf-var_actors-series_2-18",
  # "data-networks_sf-var_actors-series_2-19",
  # "data-networks_sf-var_actors-series_2-20",
  #  VAR_ACTORS SERIES 3
  # "data-networks_sf-var_actors-series_3-1",
  # "data-networks_sf-var_actors-series_3-2",
  # "data-networks_sf-var_actors-series_3-3",
  # "data-networks_sf-var_actors-series_3-4",
  # "data-networks_sf-var_actors-series_3-5",
  # "data-networks_sf-var_actors-series_3-6",
  # "data-networks_sf-var_actors-series_3-7",
  # "data-networks_sf-var_actors-series_3-8",
  # "data-networks_sf-var_actors-series_3-9",
  # "data-networks_sf-var_actors-series_3-10",
  # "data-networks_sf-var_actors-series_3-11",
  # "data-networks_sf-var_actors-series_3-12",
  # "data-networks_sf-var_actors-series_3-13",
  # "data-networks_sf-var_actors-series_3-14",
  # "data-networks_sf-var_actors-series_3-15",
  # "data-networks_sf-var_actors-series_3-16",
  # "data-networks_sf-var_actors-series_3-17",
  # "data-networks_sf-var_actors-series_3-18",
  # "data-networks_sf-var_actors-series_3-19",
  # "data-networks_sf-var_actors-series_3-20",
  #  VAR_ACTORS SERIES 4
  # "data-networks_sf-var_actors-series_4-1",
  # "data-networks_sf-var_actors-series_4-2",
  # "data-networks_sf-var_actors-series_4-3",
  # "data-networks_sf-var_actors-series_4-4",
  # "data-networks_sf-var_actors-series_4-5",
  # "data-networks_sf-var_actors-series_4-6",
  # "data-networks_sf-var_actors-series_4-7",
  # "data-networks_sf-var_actors-series_4-8",
  # "data-networks_sf-var_actors-series_4-9",
  # "data-networks_sf-var_actors-series_4-10",
  # "data-networks_sf-var_actors-series_4-11",
  # "data-networks_sf-var_actors-series_4-12",
  # "data-networks_sf-var_actors-series_4-13",
  # "data-networks_sf-var_actors-series_4-14",
  # "data-networks_sf-var_actors-series_4-15",
  # "data-networks_sf-var_actors-series_4-16",
  # "data-networks_sf-var_actors-series_4-17",
  # "data-networks_sf-var_actors-series_4-18",
  # "data-networks_sf-var_actors-series_4-19",
  # "data-networks_sf-var_actors-series_4-20",
  #  VAR_ACTORS SERIES 5
  # "data-networks_sf-var_actors-series_5-1",
  # "data-networks_sf-var_actors-series_5-2",
  # "data-networks_sf-var_actors-series_5-3",
  # "data-networks_sf-var_actors-series_5-4",
  # "data-networks_sf-var_actors-series_5-5",
  # "data-networks_sf-var_actors-series_5-6",
  # "data-networks_sf-var_actors-series_5-7",
  # "data-networks_sf-var_actors-series_5-8",
  # "data-networks_sf-var_actors-series_5-9",
  # "data-networks_sf-var_actors-series_5-10",
  # "data-networks_sf-var_actors-series_5-11",
  # "data-networks_sf-var_actors-series_5-12",
  # "data-networks_sf-var_actors-series_5-13",
  # "data-networks_sf-var_actors-series_5-14",
  # "data-networks_sf-var_actors-series_5-15",
  # "data-networks_sf-var_actors-series_5-16",
  # "data-networks_sf-var_actors-series_5-17",
  # "data-networks_sf-var_actors-series_5-18",
  # "data-networks_sf-var_actors-series_5-19",
  # "data-networks_sf-var_actors-series_5-20",
  #  VAR_HUBS SERIES 1
  # "data-networks_sf-var_hubs-series_1-1",
  # "data-networks_sf-var_hubs-series_1-2",
  # "data-networks_sf-var_hubs-series_1-3",
  # "data-networks_sf-var_hubs-series_1-4",
  # "data-networks_sf-var_hubs-series_1-5",
  # "data-networks_sf-var_hubs-series_1-6",
  # "data-networks_sf-var_hubs-series_1-7",
  # "data-networks_sf-var_hubs-series_1-8",
  # "data-networks_sf-var_hubs-series_1-9",
  # "data-networks_sf-var_hubs-series_1-10",
  # "data-networks_sf-var_hubs-series_1-11",
  # "data-networks_sf-var_hubs-series_1-12",
  # "data-networks_sf-var_hubs-series_1-13",
  # "data-networks_sf-var_hubs-series_1-14",
  # "data-networks_sf-var_hubs-series_1-15",
  # "data-networks_sf-var_hubs-series_1-16",
  # "data-networks_sf-var_hubs-series_1-17",
  # "data-networks_sf-var_hubs-series_1-18",
  # "data-networks_sf-var_hubs-series_1-19",
  # "data-networks_sf-var_hubs-series_1-20",
  #  VAR_HUBS SERIES 2
  # "data-networks_sf-var_hubs-series_2-1",
  # "data-networks_sf-var_hubs-series_2-2",
  # "data-networks_sf-var_hubs-series_2-3",
  # "data-networks_sf-var_hubs-series_2-4",
  # "data-networks_sf-var_hubs-series_2-5",
  # "data-networks_sf-var_hubs-series_2-6",
  # "data-networks_sf-var_hubs-series_2-7",
  # "data-networks_sf-var_hubs-series_2-8",
  # "data-networks_sf-var_hubs-series_2-9",
  # "data-networks_sf-var_hubs-series_2-10",
  # "data-networks_sf-var_hubs-series_2-11",
  # "data-networks_sf-var_hubs-series_2-12",
  # "data-networks_sf-var_hubs-series_2-13",
  # "data-networks_sf-var_hubs-series_2-14",
  # "data-networks_sf-var_hubs-series_2-15",
  # "data-networks_sf-var_hubs-series_2-16",
  # "data-networks_sf-var_hubs-series_2-17",
  # "data-networks_sf-var_hubs-series_2-18",
  # "data-networks_sf-var_hubs-series_2-19",
  # "data-networks_sf-var_hubs-series_2-20",
  #  VAR_HUBS SERIES 3
  # "data-networks_sf-var_hubs-series_3-1",
  # "data-networks_sf-var_hubs-series_3-2",
  # "data-networks_sf-var_hubs-series_3-3",
  # "data-networks_sf-var_hubs-series_3-4",
  # "data-networks_sf-var_hubs-series_3-5",
  # "data-networks_sf-var_hubs-series_3-6",
  # "data-networks_sf-var_hubs-series_3-7",
  # "data-networks_sf-var_hubs-series_3-8",
  # "data-networks_sf-var_hubs-series_3-9",
  # "data-networks_sf-var_hubs-series_3-10",
  # "data-networks_sf-var_hubs-series_3-11",
  # "data-networks_sf-var_hubs-series_3-12",
  # "data-networks_sf-var_hubs-series_3-13",
  # "data-networks_sf-var_hubs-series_3-14",
  # "data-networks_sf-var_hubs-series_3-15",
  # "data-networks_sf-var_hubs-series_3-16",
  # "data-networks_sf-var_hubs-series_3-17",
  # "data-networks_sf-var_hubs-series_3-18",
  # "data-networks_sf-var_hubs-series_3-19",
  # "data-networks_sf-var_hubs-series_3-20",
  #  VAR_HUBS SERIES 4
  # "data-networks_sf-var_hubs-series_4-1",
  # "data-networks_sf-var_hubs-series_4-2",
  # "data-networks_sf-var_hubs-series_4-3",
  # "data-networks_sf-var_hubs-series_4-4",
  # "data-networks_sf-var_hubs-series_4-5",
  # "data-networks_sf-var_hubs-series_4-6",
  # "data-networks_sf-var_hubs-series_4-7",
  # "data-networks_sf-var_hubs-series_4-8",
  # "data-networks_sf-var_hubs-series_4-9",
  # "data-networks_sf-var_hubs-series_4-10",
  # "data-networks_sf-var_hubs-series_4-11",
  # "data-networks_sf-var_hubs-series_4-12",
  # "data-networks_sf-var_hubs-series_4-13",
  # "data-networks_sf-var_hubs-series_4-14",
  # "data-networks_sf-var_hubs-series_4-15",
  # "data-networks_sf-var_hubs-series_4-16",
  # "data-networks_sf-var_hubs-series_4-17",
  # "data-networks_sf-var_hubs-series_4-18",
  # "data-networks_sf-var_hubs-series_4-19",
  # "data-networks_sf-var_hubs-series_4-20",
  #  VAR_HUBS SERIES 5
  # "data-networks_sf-var_hubs-series_5-1",
  # "data-networks_sf-var_hubs-series_5-2",
  # "data-networks_sf-var_hubs-series_5-3",
  # "data-networks_sf-var_hubs-series_5-4",
  # "data-networks_sf-var_hubs-series_5-5",
  # "data-networks_sf-var_hubs-series_5-6",
  # "data-networks_sf-var_hubs-series_5-7",
  # "data-networks_sf-var_hubs-series_5-8",
  # "data-networks_sf-var_hubs-series_5-9",
  # "data-networks_sf-var_hubs-series_5-10",
  # "data-networks_sf-var_hubs-series_5-11",
  # "data-networks_sf-var_hubs-series_5-12",
  # "data-networks_sf-var_hubs-series_5-13",
  # "data-networks_sf-var_hubs-series_5-14",
  # "data-networks_sf-var_hubs-series_5-15",
  # "data-networks_sf-var_hubs-series_5-16",
  # "data-networks_sf-var_hubs-series_5-17",
  # "data-networks_sf-var_hubs-series_5-18",
  # "data-networks_sf-var_hubs-series_5-19",
  # "data-networks_sf-var_hubs-series_5-20",
]

ranking_path: null

run:
  experiment_type: "main"
  max_epochs_num: -1
  patience: 1
  repetitions: 30
  random_seed: 43
