networks: [
  # "arxiv_netscience_coauthorship",
  # "aucs",
  # "ckm_physicians",
  # "eu_transportation",
  # "eu_transport_klm",
  # "lazega",
  # "l2_course_net_1",
  # "l2_course_net_2",
  # "l2_course_net_3",
  # "er1",
  # "er2",
  # "er3",
  # "er5",
  # "sf1",
  # "sf2",
  # "sf3",
  # "sf5",
  # "timik1q2009",
  "toy_network",
]

run:
  experiment_type: "brute_ds"
  max_epochs_num: -1  # this is a wildcard for unlimited allowed epochs in LTM spread instance
  random_seed: 43  # seed of the random numbers generator (to make results reproducible)

logging:
  out_dir: "./example_results"  # dir to save results in, to send them to hell use e.g. "/dev/null"
